[env]
TARGET = "aarch64-unknown-none-softfloat"
RUSTFLAGS = "-C target-cpu=cortex-a53 -C link-arg=--script=src/bsp/raspi3b/link.ld"
ELF = "target/${TARGET}/release/client"
IMG = "target/${TARGET}/release/kernel8.img"

[tasks.build]
clear = true
dependencies = ["clean", "cargo-build", "objcopy"]

[tasks.cargo-build]
command = "cargo"
args = ["rustc", "--target", "${TARGET}", "--release"]

[tasks.objcopy]
command = "rust-objcopy"
args = ["--strip-all", "-O", "binary", "${ELF}", "${IMG}"]

[tasks.test]
disabled = true
